# Generated by Django 2.2 on 2020-09-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Old_Test',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
