# Generated by Django 2.2 on 2020-09-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_book_old_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Old_Test_2',
            field=models.BooleanField(default=False),
        ),
    ]
