# Generated by Django 2.2 on 2020-09-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_auto_20200911_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Gosp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='New_Test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='Pent',
            field=models.BooleanField(default=False),
        ),
    ]
