# Generated by Django 2.2 on 2020-09-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_auto_20200911_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num_verses',
            field=models.IntegerField(null=True),
        ),
    ]
